[package]
name = "paths"
version = "0.1.0"
authors = ["gpestana <g6pestana@gmail.com>"]

[dependencies]
image = "0.20.1"
png = "0.11.0"
cairo-rs = { version = "0.2.0", features = ["png"] }
rand = "0.5.0"

