[package]
name = "squares"
version = "0.1.0"
uthors = ["gpestana <g6pestanagmail.com>"]

[dependencies]
image = "0.20.1"
png = "0.11.0"
cairo-rs = { version = "0.2.0", features = ["png"] }
rand = "0.5.0"

